---
# Secrets NAS-logo — chiffrer avec : ansible-vault encrypt inventory/group_vars/vault.yml
# Ne jamais committer ce fichier en clair.

vault_hetzner_host: "u575742.your-storagebox.de"
vault_hetzner_user: "u575742"
vault_hetzner_password: "1.Ctouthetzner"
vault_hetzner_password_obscured: "UlWnh9lJdDDnHfG4Xipta_HmXrX0xftZxFRF26IS"
vault_rclone_crypt_password: "ylVvGr4YvBvjnXbDcr8MJpM8oAXzn6of-gDYI1meRORBhLum2gKhTMG8-3-AvEKRYd3eLOUctUpKNoLm"

vault_grafana_admin_password: "L_z8GhVNHS29vR1S_iLSXFsOu2xNRgfM"

vault_tailscale_authkey: "tskey-auth-kSwAA7DXea11CNTRL-RQc5uXHat8ExSCkcjgbU9EswUohM9eKnJ"
vault_ntfy_topic: "nas-logo"
vault_immich_db_password: "L6EZnpqDOkZX2T5kRlBxoTyU6qy0rspx"

vault_github_token: "CHANGE_ME"

vault_paperless_secret_key: "WNlSF+ydSBgnIwQXwZnLjvg7Lc4p+jxOtn7Ob74RVvkl4Tx7MXoTFkbZljBW9W/3"
vault_paperless_admin_password: "LOBrxcyPQvH-K1Vo92428GKkm1OPz8Vb"
vault_immich_api_key: "KR5IYqQt14Ciacq8FOB3FKWsJb268AhccVt9ucNvsA"
vault_paperless_alban_password: "mdo7XhdQdSer4P_PV2VZZw"
vault_paperless_ilan_password: "I1Bk-n1m416O5Dh912xwMw"
vault_paperless_api_token: "6127569d86244432e8d0a64c505375eb7883cedb"
vault_meilisearch_master_key: "RuEpeN4LAI9O3K9TBA1gVqpLA2TEfz4nqhV1iVAfTNo"
vault_smb_alban_password: "Alban-NAS-2026"
vault_smb_ilan_password: "Ilan-NAS-2026"
vault_smb_alice_password: "Alice-NAS-2026"

vault_gmail_user: "loicgourmelon@gmail.com"
vault_gmail_app_password: "axevbaalohtthzxd"
vault_immich_admin_email: "loicgourmelon@gmail.com"
vault_immich_admin_password: "NasLogo2026!"
vault_immich_alban_password: "Alban-Immich-2026"
vault_immich_ilan_password: "Ilan-Immich-2026"

vault_n8n_password: "loicgourmelon@gmailA12"  
vault_n8n_encryption_key: "8e41d61ba823f3f1ea6ce714a73985eb"
vault_n8n_ssh_private_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
  QyNTUxOQAAACBbe7POU9KNTI+k1qPvnp2btpzPE8HE9t7Un0I2xTLtqgAAAKCTehfVk3oX
  1QAAAAtzc2gtZWQyNTUxOQAAACBbe7POU9KNTI+k1qPvnp2btpzPE8HE9t7Un0I2xTLtqg
  AAAEAew7WQgL+xUzoU/j9nqke4bER9TwMT+T5ciEl9ZTB4dFt7s85T0o1Mj6TWo++enZu2
  nM8TwcT23tSfQjbFMu2qAAAAFmxvaWNAbG9pYy1zb2x1dGlvbnMuZnIBAgMEBQYH
  -----END OPENSSH PRIVATE KEY-----
vault_paperless_db_password: "OWjsnwsu7CdgDf3WeJD2b9XwSj3xFC"

vault_alice_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKjPz8rmjuisk27ZDigr1IfgJ3ehLD9UK5TANIyZfgit alice-windows"
