---
- name: restart immich
  community.docker.docker_compose_v2:
    project_src: "{{ immich_install_dir }}"
    state: present
    recreate: always
    docker_cli: "{{ docker_bin }}"
  environment:
    DOCKER_HOST: "{{ docker_host }}"
