---
- name: restart monitoring
  community.docker.docker_compose_v2:
    project_src: "{{ ansible_env.HOME }}/monitoring"
    state: present
    recreate: always
    docker_cli: "{{ docker_bin }}"
  environment:
    DOCKER_HOST: "{{ docker_host }}"

- name: reload healthcheck launchagent
  ansible.builtin.command:
    cmd: launchctl load -w {{ ansible_env.HOME }}/Library/LaunchAgents/com.nas-logo.healthcheck.plist
  changed_when: false
  failed_when: false
