---
- name: reload backup launchagent
  ansible.builtin.command:
    cmd: launchctl load -w {{ ansible_env.HOME }}/Library/LaunchAgents/com.nas-logo.backup.plist
  changed_when: false
  failed_when: false
