# inventory/group_vars/vault.yml
# IMPORTANT : ce fichier doit être chiffré avec ansible-vault
# Commande : ansible-vault encrypt inventory/group_vars/vault.yml
#
# Pour éditer après chiffrement :
# ansible-vault edit inventory/group_vars/vault.yml

vault_tailscale_authkey: "tskey-auth-XXXXXXXXXXXX"
vault_hetzner_password: "votre-mot-de-passe-hetzner"
vault_immich_db_password: "mot-de-passe-db-fort"
vault_immich_jwt_secret: "secret-jwt-tres-long-et-aleatoire-minimum-32-chars"
vault_immich_admin_email: "admin@votre-domaine.com"
vault_immich_admin_password: "mot-de-passe-admin-fort"
vault_github_token: "ghp_XXXXXXXXXXXXXXXXXXXX"
